Catkin-ProjectName: genmsg
Description: Willow Garage low level build system macros and infrastructure
Author: Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard, Ken Conley
Maintainer: Ken Conley <kwc@willowgarage.com>
Homepage: http://www.ros.org/wiki/genmsg

Depends: catkin

Version: 0.3.5

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: python_distutils

